insert into public.items (id, slot, name, unlock_level, price_usd) values
  ('shirt_red', 'shirt', 'Hat Red', 1, null),
  ('shirt_blue', 'shirt', 'Frost Blue', 1, null),
  ('shirt_green', 'shirt', 'Pine', 1, null),
  ('shirt_gold', 'shirt', 'Lantern Gold', 2, null),
  ('shirt_violet', 'shirt', 'Aurora Violet', 3, null),
  ('shirt_teal', 'shirt', 'Ice Teal', 4, null),
  ('shirt_pink', 'shirt', 'Candy Pink', 5, null),
  ('shirt_snow', 'shirt', 'Snowdrift', 6, null),
  ('shirt_coal', 'shirt', 'Coal', null, 0.25),
  ('shirt_ember', 'shirt', 'Ember', null, 0.25),
  ('pants_navy', 'pants', 'Night Navy', 1, null),
  ('pants_brown', 'pants', 'Bark', 1, null),
  ('pants_grey', 'pants', 'Stone', 2, null),
  ('pants_green', 'pants', 'Fir', 3, null),
  ('pants_red', 'pants', 'Berry', 5, null),
  ('pants_snow', 'pants', 'Frost', null, 0.15),
  ('face_dots', 'face', 'Classic', 1, null),
  ('face_smile', 'face', 'Grin', 1, null),
  ('face_wow', 'face', 'Surprised', 3, null),
  ('face_wink', 'face', 'Wink', 2, null),
  ('face_shades', 'face', 'Shades', 4, null),
  ('face_beard', 'face', 'Big Beard', 6, null),
  ('face_mask', 'face', 'Scarf Mask', null, 0.3),
  ('skin_1', 'skin', 'Tone 1', 1, null),
  ('skin_2', 'skin', 'Tone 2', 1, null),
  ('skin_3', 'skin', 'Tone 3', 1, null),
  ('skin_4', 'skin', 'Tone 4', 1, null),
  ('skin_5', 'skin', 'Tone 5', 1, null),
  ('snow_white', 'snow', 'Fresh Powder', 1, null),
  ('snow_ice', 'snow', 'Glacier', 2, null),
  ('snow_pink', 'snow', 'Sugarplum', 3, null),
  ('snow_green', 'snow', 'Mint', 4, null),
  ('snow_gold', 'snow', 'Gilded', 5, null),
  ('snow_ember', 'snow', 'Ember', null, 0.25)
on conflict (id) do update set slot = excluded.slot, name = excluded.name, unlock_level = excluded.unlock_level, price_usd = excluded.price_usd;
delete from public.items where id not in ('shirt_red', 'shirt_blue', 'shirt_green', 'shirt_gold', 'shirt_violet', 'shirt_teal', 'shirt_pink', 'shirt_snow', 'shirt_coal', 'shirt_ember', 'pants_navy', 'pants_brown', 'pants_grey', 'pants_green', 'pants_red', 'pants_snow', 'face_dots', 'face_smile', 'face_wow', 'face_wink', 'face_shades', 'face_beard', 'face_mask', 'skin_1', 'skin_2', 'skin_3', 'skin_4', 'skin_5', 'snow_white', 'snow_ice', 'snow_pink', 'snow_green', 'snow_gold', 'snow_ember');
